server:
  port: 8080

sa-token:
  token-name: Authorization  # 请求头名称
  token-prefix: Bearer       # token 前缀
  timeout: 86400  # token 有效期（秒）
  is-concurrent: false  # 是否允许同一账号多设备登录
  token-type: redis  # 使用 Redis 存储 token


spring:
  application:
    name: auth-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  data:
    redis:
      database: 1
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_bipennis?useSSL=false&serverTimezone=UTC
    username: root
    password: 20021004@Dahuzi