server:
  port: 8080

spring:
  application:
    name: Auth-Service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#  data:
#    redis:
#      database: 1
#      # Redis服务器地址
#      host: 127.0.0.1
#      # Redis服务器连接端口
#      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_bipennis?useSSL=false&serverTimezone=UTC
    username: root
    password: 20021004@Dahuzi