spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          # 基础写法
          uri: http://127.0.0.1:8080
          #负载均衡写法
          #          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://127.0.0.1:8081
          #          uri: lb://user-service
          predicates:
            - Path=/user/**